### ISSUE TITLE
失效了。。？

### ISSUE THREAD

**Issue by 3fatty** [TinsFox/github-hosts#2]
![image](https://github.com/user-attachments/assets/9c434830-7550-42bf-86e8-48600bb8af9a)
![image](https://github.com/user-attachments/assets/ebb0fcd7-a786-492c-b6ef-18e17fb251cb)

**Comment by TinsFox** [comment]
这种方法不能保证稳定使用。
你可以
1. 自己部署一个，失效的时候手动更新 DNS 解析抓取新的 IP
2. 等待我部署的下一次更新后尝试

**Comment by 3fatty** [comment]
> 这种方法不能保证稳定使用。 你可以
> 
> 1. 自己部署一个，失效的时候手动更新 DNS 解析抓取新的 IP
> 2. 等待我部署的下一次更新后尝试

谢谢回复，换了 ip 就好了
